<a href="https://colab.research.google.com/github/masatsuneki/hello-world/blob/master/20220610_rater_agreement_sscore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install agreement

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy  as np


In [ ]:
data = """10	0	0
10	0	0
10	0	0
10	0	0
9	1	0
10	0	0
10	0	0
9	1	0
9	1	0
10	0	0
10	0	0
10	0	0
10	0	0
9	1	0
10	0	0
9	1	0
10	0	0
10	0	0
10	0	0
10	0	0
10	0	0
10	0	0
10	0	0
10	0	0
9	1	0
"""

In [ ]:
row = []
rows = []
for i, d in enumerate(data.split()):
  row.append(int(d))
  if len(row) == 3:
    rows.append(row)
    row = []

In [ ]:
questions_answers_table = np.array(rows)

In [ ]:
print(questions_answers_table)

[[10  0  0]
 [10  0  0]
 [10  0  0]
 [10  0  0]
 [ 9  1  0]
 [10  0  0]
 [10  0  0]
 [ 9  1  0]
 [ 9  1  0]
 [10  0  0]
 [10  0  0]
 [10  0  0]
 [10  0  0]
 [ 9  1  0]
 [10  0  0]
 [ 9  1  0]
 [10  0  0]
 [10  0  0]
 [10  0  0]
 [10  0  0]
 [10  0  0]
 [10  0  0]
 [10  0  0]
 [10  0  0]
 [ 9  1  0]]


In [ ]:
from agreement import metrics

In [ ]:
metrics.s_score(questions_answers_table)

0.9279999999999999